name: CICD

on:
  workflow_dispatch:

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: PM2-IT22taWIN-muon-pero-pasu/team07-Lucky7-projekt1-racetrack
          github-server-url: https://github.zhaw.ch
          token: ${{ secrets.ZHAW_GITHUB_API }}
          fetch-depth: 0