name: Pull Request

on:
  repository_dispatch:
    types: [pull-request]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: PM2-IT22taWIN-muon-pero-pasu/team07-Lucky7-projekt1-racetrack
          github-server-url: https://github.zhaw.ch
          token: ${{ secrets.ZHAW_GITHUB_API }}
          fetch-depth: 0
          
      - name: Create Draft Pull Request
        run: |
          body=$(cat .github/PULL_REQUEST_TEMPLATE.md)
          branch=$(echo "${{ github.event.client_payload.ref }}" | sed 's/refs\/heads\///')
          if [[ "$branch" =~ ^(feat|build|chore|ci|docs|fix|refactor|revert|test)(\/|\#)[A-Za-z0-9_]+$ ]]; then
            topic=$(echo "$branch" | cut -d '/' -f 1)
          else
            topic="feat"
          fi
          creator=$(echo "${{ github.event.client_payload.sender.login }}")
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.ZHAW_GITHUB_API }}" \
            -X POST \
             -d "{\"title\":\"$branch\",\"body\":\"$body\",\"draft\":true,\"head\":\"$branch\",\"base\":\"main\",\"maintainer_can_modify\":true,\"labels\":[\"$topic\"],\"assignees\":[\"$creator\"]}" \
            "https://github.zhaw.ch/api/v3/repos/PM2-IT22taWIN-muon-pero-pasu/team07-Lucky7-projekt1-racetrack/pulls")
